server:
  port: 8088
  
spring:
   application:
    name: CLOUD-CONFIG-SERVER
   cloud :
     config:
      server : 
       git:
        uri: https://github.com/dilip-reddy421/config-server/tree/main
      
    