
server:  port: 8089
  
spring:  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass@word1
    url: jdbc:mysql://localhost:3306/marketplace?createDatabaseIfNotExist=true&useSSL=false
      jpa:    generate-ddl: true
    hibernate:      ddl-auto: update  application:    name: COMPANY-SERVICE
  mvc:    pathmatch:      matching-strategy: ant-path-matcher
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      
  config:
       import : "optional:configserver: http://localhost:8088"
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone : http://localhost:8761/eureka
      